# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build manager facebook_service

on:
  push:
    branches: [manager]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull code and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd facebook_service_manager
            git fetch
            git checkout manager
            git checkout -- .
            git pull
            pm2 restart manager
            pm2 save