name: Deploy

on:
  push:
    branches:
      - web_manager

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
          check-latest: true
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
      - run: |
          cd web_manager
          git fetch
          git checkout web_manager
          git pull
      - run: npm run build
      - run: |
          pm2 restart web_manager
          pm2 save